ARG BASE_IMAGE=ghcr.io/dosquartsdedocs/unaltraweb-compute-python@sha256:18cb269811bd4005800382da25a480ec2bca7eac8d0501ad1ef36bad1c0f8cd9
FROM ${BASE_IMAGE}

COPY requirements-compute.txt /tmp/requirements-compute.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements-compute.txt
