@startfiles
/tigit_grup_XX/
/tigit_grup_XX/dades_originals/
/tigit_grup_XX/dades_processades/
/tigit_grup_XX/qgis/
/tigit_grup_XX/qgis/projecte.qgz
/tigit_grup_XX/figures/
/tigit_grup_XX/infografia/
/tigit_grup_XX/lliuraments/
@endfiles
