timeline
  title Traça d'una figura
  Font : Portal oficial i metadades
  Taula : Neteja, denominadors i unitats
  Visualització : Tipus de gràfic i retolació
  Publicació : SVG, PDF i cita de la font
