name: Deploy site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: dosquartsdedocs/unaltraweb/.github/workflows/site-deploy.yml@94e964c4d893689a9d1c905157e63f2265403552
    with:
      install-python-requirements: false
      check-manual-pdf: true
      vegavisuals-sha: 8ec068216d1340b1a4ae0c970f116f57325fb78c
