name: Deploy site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: dosquartsdedocs/unaltraweb/.github/workflows/site-deploy.yml@8def503b31b0821ba832ab67c961902e090efb9d
    with:
      install-python-requirements: false
      check-manual-pdf: true
      vegavisuals-sha: 8ec068216d1340b1a4ae0c970f116f57325fb78c
